apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi
  namespace: devesh-app-ns
  labels:
    app: authapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
      - name: authapi
        image: tgacapstonecontainerregistry.azurecr.io/devmakke1/capstone/auth.api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080