apiVersion: v1
kind: Pod
metadata:
  name: authapi
  namespace: devesh-app-ns
spec:
  containers:
  - name: authapi
    image: tgacapstonecontainerregistry.azurecr.io/devmakke1/capstone/auth.api:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080