// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Order.Data.Context;

#nullable disable

namespace Order.Data.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20250405061039_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Order.Common.Model.OrderDetails", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            AddressId = 1,
                            CustomerId = 1,
                            PaymentId = 1,
                            StripeSessionId = "1",
                            status = "Complete"
                        },
                        new
                        {
                            OrderId = 2,
                            AddressId = 3,
                            CustomerId = 2,
                            PaymentId = 2,
                            StripeSessionId = "2",
                            status = "Complete"
                        });
                });

            modelBuilder.Entity("Order.Common.Model.OrderItemDetails", b =>
                {
                    b.Property<int>("OrderItemDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderItemDetailsId"));

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerItem")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemDetailsId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItemDetails");

                    b.HasData(
                        new
                        {
                            OrderItemDetailsId = 1,
                            DiscountPercentage = 30,
                            OrderId = 1,
                            PricePerItem = 20000m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemDetailsId = 2,
                            DiscountPercentage = 20,
                            OrderId = 2,
                            PricePerItem = 5000m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemDetailsId = 3,
                            DiscountPercentage = 30,
                            OrderId = 2,
                            PricePerItem = 6000m,
                            ProductId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Order.Common.Model.OrderItemDetails", b =>
                {
                    b.HasOne("Order.Common.Model.OrderDetails", "order")
                        .WithMany("orderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("Order.Common.Model.OrderDetails", b =>
                {
                    b.Navigation("orderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
